# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
