# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_auto_20171211_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='dob',
            field=models.DateField(),
        ),
    ]
